version: '3.8'

services:
   pgadmin:
      container_name: pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: mail@example.com
        PGADMIN_DEFAULT_PASSWORD: root123456
      ports:
        - '5050:80'

   postgredb:
      container_name: postgredb
      image: postgres:14.3-alpine
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
      ports:
        - '5432:5432'
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
